name=JoyPi_Advanced_Arduino
version=1.0.0
author=Joy-IT <support@joy-it.de>
maintainer=Joy-IT <support@joy-it.de>
paragraph=sentence=This library is a collection for the Arduino for two modules on the Joy-Pi Advanced. See [here](https://www.joy-pi.net) for more information.
category=Sensors
url=https://github.com/joy-it/JoyPi_Advanced_Arduino
architectures=avr
includes=ADC.h,Gyroscope.h,Keypad_MCP.h
depends=MFRC522,Adafruit NeoPixel,Keypad,Keypad_MCP,OneWire,Servo,VEML6040,Adafruit MPR121,Adafruit BusIO,DHT sensor library,hd44780,Adafruit GFX Library,Adafruit LED Backpack Library,IRremote,Adafruit SSD1306, Adafruit ST7735 and ST7789 Library,RTCDS1307,MS5xxx